//图片选择目标对话框 action type
export const OPEN_IMAGE_SELECT_DIALOG = 'OPEN_IMAGE_SELECT_DIALOG';
export const CANCLE_IMAGE_SELECT_DIALOG = 'CANCLE_IMAGE_SELECT_DIALOG';
export const SUBMIT_IMAGE_SELECT_DIALOG = 'SUBMIT_IMAGE_SELECT_DIALOG';
// 视频选择目标对话框 action type
export const OPEN_VIDEO_SELECT_DIALOG = 'OPEN_VIDEO_SELECT_DIALOG';
export const CANCLE_VIDEO_SELECT_DIALOG = 'CANCLE_VIDEO_SELECT_DIALOG';
export const SUBMIT_VIDEO_SELECT_DIALOG = 'SUBMIT_VIDEO_SELECT_DIALOG';
